### ISSUE TITLE
Variable Font Support

### ISSUE THREAD

**Issue by rememberlenny** [figma/community#2]
**Is your feature request related to a problem? Please describe.**
Can Figma support variable fonts and create a UI for manipulating the `variation-settings` CSS parameter? These are important design elements that are available in browsers, but are not usable in old-world design software. Figma would be leading the design world if it support VF.

**Describe the solution you'd like**
Fonts with variable headings and `variation-settings` should have sliders/ui for manipulating and visualizing the results.

**Describe alternatives you've considered**
Without support, there aren't any alternatives. Only other option is to use font instances.

**Additional context**
https://www.typenetwork.com/brochure/opentype-font-variations/
https://opentype.js.org/font-inspector.html
https://www.axis-praxis.org/specimens/__DEFAULT__

**Comment by rememberlenny** [comment]
@dfield ^^

**Comment by rememberlenny** [comment]
Thank you @neversitdull

**Comment by ian-cox** [comment]
With [variable fonts supported in all modern browsers](https://caniuse.com/#search=variable%20font) I would love to have access to these features.

**Comment by himichelleng** [comment]
+1 for this request!

**Comment by be5invis** [comment]
+1

**Comment by AdamSabla** [comment]
+1

**Comment by rememberlenny** [comment]
I am building a Variable Fonts plugin for Figma. It's not going to be fully
integrated with the Figma UI, due to the limitations of the Figma rendering
engine (which is awesome). It will let you render text in the Figma canvas
and control a Variable Font's properties using a control panel.

If you are interested in learning more, please let me know:
Lenny@publicart.io

--
*Leonard Bogdonoff*
rememberlenny@gmail.com
Blog <http://medium.com/@rememberlenny> | Portfolio
<http://rememberlenny.com/> | @rememberlenny
<http://twitter.com/rememberlenny>
949-322-8496

**Comment by tedmcdo** [comment]
+1

**Comment by luismqueral** [comment]
+1 😬

**Comment by dallasbpeters** [comment]
👍

**Comment by TomS-** [comment]
@rememberlenny How is that going? I have a variable font and I can see all the different weights but selecting them changes nothing. It would be amazing to have support for this.

**Comment by rememberlenny** [comment]
@TomS- I've heard interest, but no concrete action planned.

**Comment by glyphe** [comment]
Wish it would work since Sketch now also supports it.

**Comment by benbalderas** [comment]
+1

This should definitely be a priority

**Comment by jamesgaddum** [comment]
+1!

**Comment by ponchofreedo** [comment]
+1

**Comment by eagleeyejack** [comment]
+1

**Comment by ximenavf92** [comment]
+1

**Comment by robinisaksson** [comment]
+1

**Comment by olgageletina** [comment]
+1 – Sketch supports variable fonts well by auto detecting the axises

**Comment by rememberlenny** [comment]
Hello all!

I made the original post and am now building a plug-in to use variable fonts.

You can foow the progress here:

https://twitter.com/rememberlenny/status/1259740133739421699?s=21

**Comment by rememberlenny** [comment]
Major breakthrough!

The variable fonts render in the plugin iframe, and I'm able to use a JavaScript library to read the font header data to pull the axis information. Here is what I have working so far!

![May-12-2020 04-01-17](https://user-images.githubusercontent.com/1332366/81658332-aa885f00-9406-11ea-97af-e0beef08f66a.gif)
<img width="783" alt="Screen Shot 2020-05-12 at 4 09 17 AM" src="https://user-images.githubusercontent.com/1332366/81658348-ad834f80-9406-11ea-8c71-40b77adb3eb1.png">

Plugin code for this is here: https://github.com/rememberlenny/figma-variable-fonts
Design file for this is here: https://www.figma.com/community/file/841567018431192369/Figma-Variable-Font-Plugin-design

**Comment by luismqueral** [comment]
Nice! Thanks for the contribution :-)

**Comment by grillitype** [comment]
+1000

**Comment by aaronmartin-rl** [comment]
Please soon!

**Comment by kuvahaku** [comment]
+1

**Comment by sandersturing** [comment]
Is there any news on this? The request is from more than a year ago, but it seems like quite a important and basic feature to have in (digital) design software nowadays?

We switched to Figma from Sketch for a project, but our design heavily relies on variable fonts. This actually makes Figma unusable for this project at this point, right?

**Comment by jorgeneidem** [comment]
+1, our team recently switched to Figma and I was very surprised to discover the lack of support for variable fonts, as Sketch has supported this since v59 (October 2019). 

@sandersturing I had the same thought, but most variable fonts also come as font instances. You could install those for use in Figma, and if your product uses other variable weights, you can design for approximation using the instances closest to your variable weights until support arrives. It's not optimal, but also far from unusable.

**Comment by sandersturing** [comment]
> t's not optimal, but also far from unusable

@jorgeneidem Thanks for the suggestion. In the case of this specific project it doesn't help much. We use the variable width to make text fill out the space it can take up. So obviously this is a different value for every word, phrase and situation. But we will relook at Figma for future projects.

**Comment by davelab6** [comment]
https://github.com/rememberlenny/figma-variable-fonts

**Comment by grillitype** [comment]
Just wanted to add our support for this feature 👍 We’re already shipping variable fonts, but need the industry tools like Figma to support them so it actually makes sense for our typefaces’ users to put them to good use.

**Comment by arrowtype** [comment]
Shipping a typography tool that doesn’t support variable fonts is a bit like shipping a color picker that only supports a limited palette of preset swatches, rather than the 256³ (16 million) possible colors from RGB values. 

Limited color presets are obviously handy in some cases, but would be a pretty big absence of user control in a pro tool like Figma. Limited type style presets are similarly constricting when near-infinite possibilities could be readily available!

**Comment by chrissimpkins** [comment]
+1

**Comment by oolong32** [comment]
Variable Fonts are part of the latest OpenType standard and not some flash in the pan. I for my part would be very sorry to see Figma lose its advantage over XD because of lack of support of standard technology.

**Comment by jon-lehman** [comment]
+1 for variable font support in Figma. Was super excited to jam with a sweet new variable font I picked up and was sad to see Figma still doesn't support them.

**Comment by davelab6** [comment]
Apparently Figma folks want to see more case studies of VFs used in shipped
product at scale.

**Comment by alexalspaugh** [comment]
Here's [a great talk](https://developer.apple.com/videos/play/wwdc2020/10175/) from Apple that goes over using variable fonts and why they're helpful. Can't get much more at scale than IOS. Would love to see this supported in Figma.

**Comment by alexfjelldal** [comment]
OH YES PLEASE!

**Comment by jecl** [comment]
I need this in my life!

**Comment by seq000** [comment]
+1 for variable font support in Figma.

**Comment by vitavalka** [comment]
**Also +1** as it seems fonts are a mess in Figma. I'm currently playing with it and fonts in Sketch are fine, while they're not fine in Figma. Eg. **Inter**

**Comment by MrBushid0** [comment]
+1

**Comment by danielcampos15** [comment]
**Not yet?!** Figma is kidding...

**+1**
